@url=http://localhost:3000

### registro de usuario
POST {{url}}/api/auth/registro
Content-Type: application/json

{
    "email": "alediaz@gmail.com",
    "nombre": "Alejandro",
    "password": "43611679a"
}

### Login
# @name login
POST {{url}}/api/auth/login
Content-Type: application/json

{
    "email": "alediaz@gmail.com",
    "password": "43611679a"
}

###
@token = {{login.response.body.token}}

### Verificar token
GET {{url}}/api/auth/verify
Authorization: Bearer {{token}}
