@url=http://localhost:3000

### Login
# @name login
POST {{url}}/api/auth/login
Content-Type: application/json

{
    "email": "alekey@gmail.com",
    "password": "123456"
}

###
@token = {{login.response.body.token}}

### mostrar todas las materias
GET {{url}}/api/materias
Authorization: Bearer {{token}}

###  obtener materia por id
GET {{url}}/api/materias/1
Authorization: Bearer {{token}}

### crear una nueva materia
POST {{url}}/api/materias
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "nombre": "Matemática",
    "codigo": "MAT1",
    "anio": 1
}

### actualizar una materia
PUT {{url}}/api/materias/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "nombre": "Matemática",
    "codigo": "MAT2",
    "anio": 2
}

### eliminar una materia
DELETE {{url}}/api/materias/1
Authorization: Bearer {{token}}
