@url=http://localhost:3000

### Login
# @name login
POST {{url}}/api/auth/login
Content-Type: application/json
{
    "email": "alekey@gmail.com",
    "password": "123456"
}

###
@token = {{login.response.body.token}}

### mostrar notas de un alumno
GET {{url}}/api/notas/alumno/1
Authorization: Bearer {{token}}

### mostrar notas de una materia
GET {{url}}/api/notas/materia/1
Authorization: Bearer {{token}}

### crear o actualizar una nota
POST {{url}}/api/notas
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "alumno_id": 1,
    "materia_id": 1,
    "nota1": 8.5,
    "nota2": 3.0,
    "nota3": 4.5
}

### Actualizar notas de un alumno
PUT {{url}}/api/notas/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "nota1": 8.5,
    "nota2": 3.0,
    "nota3": 4.5
}

